spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_schema: PUBLIC
        dialect: org.hibernate.dialect.H2Dialect
        id:
          new_generator_mappings: true
        search:
          default:
            directory_provider: local-heap
          lucene_version: LATEST
        temp:
          use_jdbc_metadata_defaults: false
  data:
    jpa:
      repositories:
        bootstrap_mode: default

logging:
  level:
    root: INFO
    com.example.demo: DEBUG

